# Calculating drawdown values for refined trading strategy

In [44]:
# Basic libraries 
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pykalman import KalmanFilter
from itertools import combinations
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import coint
import statsmodels.api as sm
import pickle
import os
import sys

PROJECT_ROOT = os.path.abspath("..")
sys.path.insert(0, PROJECT_ROOT)

In [45]:
# Scripts 
from src.local_config import *
from src.drawdown_optimisation import * 
from src.volatility_plot import *

In [46]:
# Load dictionaries from previous notebook
# In-Sample
with open(PROJECT_ROOT / "data/dictionaries/static_spreads_is.pkl", "rb") as f:
    static_spreads_is = pickle.load(f)
with open(PROJECT_ROOT / "data/dictionaries/static_models_is.pkl", "rb") as f:
    static_models_is = pickle.load(f)

with open(PROJECT_ROOT / "data/dictionaries/dynamic_spreads_is.pkl", "rb") as f:
    dynamic_spreads_is = pickle.load(f)
with open(PROJECT_ROOT / "data/dictionaries/dynamic_details_is.pkl", "rb") as f:
    dynamic_details_is = pickle.load(f)

# Out-Of-Sample
with open(PROJECT_ROOT / "data/dictionaries/static_spreads_oos.pkl", "rb") as f:
    static_spreads_oos = pickle.load(f)
with open(PROJECT_ROOT / "data/dictionaries/static_models_oos.pkl", "rb") as f:
    static_models_oos = pickle.load(f)

with open(PROJECT_ROOT / "data/dictionaries/dynamic_spreads_oos.pkl", "rb") as f:
    dynamic_spreads_oos = pickle.load(f)
with open(PROJECT_ROOT / "data/dictionaries/dynamic_details_oos.pkl", "rb") as f:
    dynamic_details_oos = pickle.load(f)

In [47]:
# Load pairs
with open(PROJECT_ROOT / "data/pairs_is.pkl", "rb") as f:
    pairs_is = pickle.load(f)
with open(PROJECT_ROOT / "data/pairs_oos.pkl", "rb") as f:
    pairs_oss = pickle.load(f)

In [48]:
# Trading Signals
with open(PROJECT_ROOT / "data/dictionaries/is_results.pkl", "rb") as f:
    is_results = pickle.load(f)
with open(PROJECT_ROOT / "data/dictionaries/is_trading_signals.pkl", "rb") as f:
    is_trading_signals = pickle.load(f)

with open(PROJECT_ROOT / "data/dictionaries/oos_results.pkl", "rb") as f:
    oos_results = pickle.load(f)
with open(PROJECT_ROOT / "data/dictionaries/oos_trading_signals.pkl", "rb") as f:
    oos_trading_signals = pickle.load(f)

## Estimated Volatility Formula
Calculated in calculate_vol function:
$$
\hat{\sigma_t}=\sqrt{\frac{\sum_{i=0}^tw_i(r_{t-i}-\mu_t)^2}{\sum_{i=0}^tw_i}}
$$

## Drawdown Threshold Formula
Calculated in drawdown_thresholds function:
$$
\text{Drawdown}=k_{m}\times\sigma_{i,t}\times\sqrt{H}
$$

Where:
- m is either the volatility multiplier coefficient for **reducing** position size or **closing** a position
- $\sigma_{i,t}$ is the estimated volatility from above for pair i
- H is the holding period (which we have fixed to 10 days for simplicity)

## In-Sample

In [49]:
is_results

{'entry_1.5_exit_0.0': {('700 HK Equity vs 1347 HK Equity',
   0.5):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  4.846201  2.153853  1.155692  1.735673 -0.047875      0.5
  2015-03-31  4.863326  2.154897  1.157182  1.734420 -0.031353      0.5
  2015-04-01  4.868749  2.185602  1.162357  1.730626 -0.076066      0.5
  2015-04-02  4.880838  2.193663  1.167672  1.726793 -0.074835      0.5
  2015-04-08  4.911728  2.287167  1.194148  1.710678 -0.195027      0.5
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  6.207606  3.808062  4.174089  0.568151 -0.130036      0.5
  2020-12-28  6.138742  3.793667  4.176448  0.564741 -0.180147      0.5
  2020-12-29  6.160659  3.816833  4.178816  0.561604 -0.161706      0.5
  2020-12-30  6.213882  3.820105  4.180271  0.559606 -0.104144      0.5
  2020-12-31  6.221892  3.775653  4.180828  0.558433 -0.067384      0.5

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30      0.125397     0.067909 -2.551542       1.0
  2015-03-31      0.118729     0.063079 -2.379277       1.0
  2015-04-01      0.114005     0.066829 -2.844125       1.0
  2015-04-02      0.110307     0.070980 -2.608356       1.0
  2015-04-08      0.104540     0.080972 -3.699636       1.0
  ...                  ...          ...       ...       ...
  2020-12-24     -0.030540     0.072944 -1.363997       1.0
  2020-12-28     -0.033248     0.075432 -1.947439       1.0
  2020-12-29     -0.034641     0.077029 -1.649586       1.0
  2020-12-30     -0.035423     0.077499 -0.886733       1.0
  2020-12-31     -0.036660     0.077405 -0.396929       1.0

  [1419 rows x 10 columns],
  ('700 HK Equity vs 1347 HK Equity',
   1.0):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  4.846201  2.153853  1.036393  1.782127 -0.028633      1.0
  2015-03-31  4.863326  2.154897  1.036663  1.781828 -0.012993      1.0
  2015-04-01  4.868749  2.185602  1.038577  1.780119 -0.060458      1.0
  2015-04-02  4.880838  2.193663  1.040625  1.778344 -0.060874      1.0
  2015-04-08  4.911728  2.287167  1.053406  1.769700 -0.189277      1.0
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  6.207606  3.808062  3.860973  0.662206 -0.175090      1.0
  2020-12-28  6.138742  3.793667  3.863828  0.658963 -0.224971      1.0
  2020-12-29  6.160659  3.816833  3.866705  0.655876 -0.209414      1.0
  2020-12-30  6.213882  3.820105  3.868727  0.653659 -0.151891      1.0
  2020-12-31  6.221892  3.775653  3.869775  0.652182 -0.110298      1.0

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30      0.162640     0.098159 -1.948595       1.0
  2015-03-31      0.151044     0.073728 -2.224890       1.0
  2015-04-01      0.143628     0.072210 -2.826290       1.0
  2015-04-02      0.138097     0.074947 -2.654812       1.0
  2015-04-08      0.130844     0.084753 -3.777102       1.0
  ...                  ...          ...       ...       ...
  2020-12-24     -0.043977     0.088880 -1.475178       1.0
  2020-12-28     -0.047464     0.091809 -1.933434       1.0
  2020-12-29     -0.049504     0.094035 -1.700537       1.0
  2020-12-30     -0.050940     0.094941 -1.063300       1.0
  2020-12-31     -0.052854     0.094961 -0.604925       1.0

  [1419 rows x 10 columns],
  ('700 HK Equity vs 1347 HK Equity',
   5.0):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  4.846201  2.153853  0.905485  1.808859  0.044700      5.0
  2015-03-31  4.863326  2.154897  0.905409  1.809431  0.058779      5.0
  2015-04-01  4.868749  2.185602  0.905378  1.809523  0.008475      5.0
  2015-04-02  4.880838  2.193663  0.905354  1.809587  0.005860      5.0
  2015-04-08  4.911728  2.287167  0.906798  1.807708 -0.129599      5.0
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  6.207606  3.808062  2.898584  0.959654 -0.345398      5.0
  2020-12-28  6.138742  3.793667  2.902173  0.956641 -0.392611      5.0
  2020-12-29  6.160659  3.816833  2.905856  0.953635 -0.385062      5.0
  2020-12-30  6.213882  3.820105  2.908956  0.951087 -0.328327      5.0
  2020-12-31  6.221892  3.775653  2.911152  0.949101 -0.272736      5.0

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30      0.368218     0.322920 -1.001854       0.0
  2015-03-31      0.333504     0.226653 -1.212093       0.0
  2015-04-01      0.310096     0.181259 -1.664036       1.0
  2015-04-02      0.292499     0.156637 -1.829962       1.0
  2015-04-08      0.275626     0.146151 -2.772654       1.0
  ...                  ...          ...       ...       ...
  2020-12-24     -0.132392     0.131142 -1.624234       1.0
  2020-12-28     -0.137846     0.135054 -1.886385       1.0
  2020-12-29     -0.141435     0.138727 -1.756152       1.0
  2020-12-30     -0.144488     0.140810 -1.305579       1.0
  2020-12-31     -0.148130     0.141261 -0.882100       1.0

  [1419 rows x 10 columns],
  ('1347 HK Equity vs 268 HK Equity',
   0.5):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  2.153853  1.186318  1.444700  0.664969 -0.079711      0.5
  2015-03-31  2.154897  1.171243  1.453702  0.653774 -0.064534      0.5
  2015-04-01  2.185602  1.253905  1.468757  0.635849 -0.080450      0.5
  2015-04-02  2.193663  1.300736  1.487347  0.614056 -0.092410      0.5
  2015-04-08  2.287167  1.458150  1.509723  0.588773 -0.081074      0.5
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  3.808062  3.323236  1.473745  0.665160  0.123834      0.5
  2020-12-28  3.793667  3.303217  1.473583  0.666998  0.116846      0.5
  2020-12-29  3.816833  3.349904  1.473123  0.668743  0.103485      0.5
  2020-12-30  3.820105  3.386084  1.472606  0.670126  0.078395      0.5
  2020-12-31  3.775653  3.453157  1.472719  0.669926 -0.010426      0.5

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30     -0.035783     0.114290 -0.384357       0.0
  2015-03-31     -0.045036     0.091059 -0.214124       0.0
  2015-04-01     -0.050818     0.081454 -0.363796       0.0
  2015-04-02     -0.055952     0.073715 -0.494585       0.0
  2015-04-08     -0.059549     0.069388 -0.310212       0.0
  ...                  ...          ...       ...       ...
  2020-12-24      0.050382     0.087758  0.836992      -1.0
  2020-12-28      0.052814     0.087540  0.731457      -1.0
  2020-12-29      0.053514     0.087778  0.569290      -1.0
  2020-12-30      0.054061     0.087830  0.277059      -1.0
  2020-12-31      0.054501     0.087432 -0.742608      -1.0

  [1419 rows x 10 columns],
  ('1347 HK Equity vs 268 HK Equity',
   1.0):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  2.153853  1.186318  1.309488  0.805174 -0.110828      1.0
  2015-03-31  2.154897  1.171243  1.316950  0.795102 -0.093311      1.0
  2015-04-01  2.185602  1.253905  1.330121  0.778384 -0.120539      1.0
  2015-04-02  2.193663  1.300736  1.346836  0.757637 -0.138659      1.0
  2015-04-08  2.287167  1.458150  1.371730  0.728232 -0.146434      1.0
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  3.808062  3.323236  1.449620  0.662762  0.155928      1.0
  2020-12-28  3.793667  3.303217  1.449309  0.664476  0.149450      1.0
  2020-12-29  3.816833  3.349904  1.448779  0.666137  0.136560      1.0
  2020-12-30  3.820105  3.386084  1.448202  0.667548  0.111530      1.0
  2020-12-31  3.775653  3.453157  1.448037  0.667840  0.021460      1.0

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30     -0.003887     0.168221 -0.635718       0.0
  2015-03-31     -0.018787     0.131282 -0.567658       0.0
  2015-04-01     -0.028794     0.114431 -0.801753       0.0
  2015-04-02     -0.037378     0.102184 -0.991159       0.0
  2015-04-08     -0.044225     0.095141 -1.074282       0.0
  ...                  ...          ...       ...       ...
  2020-12-24      0.056700     0.096334  1.030050      -1.0
  2020-12-28      0.059629     0.096439  0.931380      -1.0
  2020-12-29      0.060824     0.096948  0.781204      -1.0
  2020-12-30      0.061859     0.097155  0.511259      -1.0
  2020-12-31      0.062780     0.096493 -0.428210      -1.0

  [1419 rows x 10 columns],
  ('1347 HK Equity vs 268 HK Equity',
   5.0):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  2.153853  1.186318  1.114592  0.944755 -0.081519      5.0
  2015-03-31  2.154897  1.171243  1.115369  0.942652 -0.064547      5.0
  2015-04-01  2.185602  1.253905  1.117456  0.938268 -0.108354      5.0
  2015-04-02  2.193663  1.300736  1.120648  0.932120 -0.139428      5.0
  2015-04-08  2.287167  1.458150  1.127295  0.921352 -0.183598      5.0
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  3.808062  3.323236  1.326763  0.683029  0.211434      5.0
  2020-12-28  3.793667  3.303217  1.326163  0.684253  0.207269      5.0
  2020-12-29  3.816833  3.349904  1.325483  0.685454  0.195143      5.0
  2020-12-30  3.820105  3.386084  1.324816  0.686536  0.170621      5.0
  2020-12-31  3.775653  3.453157  1.324441  0.687063  0.078676      5.0

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30      0.209374     0.351265 -0.828129       0.0
  2015-03-31      0.181307     0.300262 -0.818799       0.0
  2015-04-01      0.158217     0.265871 -1.002633       0.0
  2015-04-02      0.137702     0.238745 -1.160781       0.0
  2015-04-08      0.119497     0.219857 -1.378604       0.0
  ...                  ...          ...       ...       ...
  2020-12-24      0.069708     0.108831  1.302258      -1.0
  2020-12-28      0.073356     0.109723  1.220458      -1.0
  2020-12-29      0.075277     0.110843  1.081402      -1.0
  2020-12-30      0.077040     0.111513  0.839191      -1.0
  2020-12-31      0.078691     0.110778 -0.000135      -1.0

  [1419 rows x 10 columns],
  ('1088 HK Equity vs 3993 HK Equity',
   0.5):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  1.973247  0.344299  1.925246  0.344019 -0.070444      0.5
  2015-03-31  1.976301  0.327864  1.926498  0.332735 -0.059288      0.5
  2015-04-01  1.982380  0.389336  1.929496  0.312845 -0.068918      0.5
  2015-04-02  2.003640  0.500169  1.935354  0.280326 -0.071924      0.5
  2015-04-08  2.028017  0.696143  1.945853  0.228075 -0.076610      0.5
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  2.162863  1.318283  1.794604  0.290170 -0.014268      0.5
  2020-12-28  2.165619  1.469026  1.795341  0.288323 -0.053276      0.5
  2020-12-29  2.160215  1.456753  1.796000  0.286571 -0.053248      0.5
  2020-12-30  2.151995  1.493578  1.796974  0.284179 -0.069422      0.5
  2020-12-31  2.149317  1.509397  1.798029  0.281631 -0.073805      0.5

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30      0.012996     0.129094 -0.646347       0.0
  2015-03-31      0.000368     0.092897 -0.642179       0.0
  2015-04-01     -0.007690     0.075748 -0.808317       0.0
  2015-04-02     -0.013796     0.064978 -0.894581       0.0
  2015-04-08     -0.018841     0.057339 -1.007481       0.0
  ...                  ...          ...       ...       ...
  2020-12-24      0.030107     0.030659 -1.447331       1.0
  2020-12-28      0.027971     0.031925 -2.544920       1.0
  2020-12-29      0.025788     0.032928 -2.400252       1.0
  2020-12-30      0.023368     0.034490 -2.690350       1.0
  2020-12-31      0.021150     0.036369 -2.610831       1.0

  [1419 rows x 10 columns],
  ('1088 HK Equity vs 3993 HK Equity',
   1.0):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  1.973247  0.344299  1.905253  0.376922 -0.061779      1.0
  2015-03-31  1.976301  0.327864  1.905433  0.371738 -0.051012      1.0
  2015-04-01  1.982380  0.389336  1.906442  0.361714 -0.064891      1.0
  2015-04-02  2.003640  0.500169  1.909259  0.342764 -0.077059      1.0
  2015-04-08  2.028017  0.696143  1.916288  0.303940 -0.099857      1.0
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  2.162863  1.318283  1.746733  0.333401 -0.023387      1.0
  2020-12-28  2.165619  1.469026  1.747347  0.331713 -0.069022      1.0
  2020-12-29  2.160215  1.456753  1.747901  0.330105 -0.068568      1.0
  2020-12-30  2.151995  1.493578  1.748696  0.327980 -0.086566      1.0
  2020-12-31  2.149317  1.509397  1.749563  0.325712 -0.091874      1.0

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30      0.068407     0.194216 -0.670316       0.0
  2015-03-31      0.050020     0.145650 -0.693666       0.0
  2015-04-01      0.037333     0.119138 -0.858026       0.0
  2015-04-02      0.027396     0.101884 -1.025231       0.0
  2015-04-08      0.018864     0.089847 -1.321357       0.0
  ...                  ...          ...       ...       ...
  2020-12-24      0.024864     0.031955 -1.509957       1.0
  2020-12-28      0.022567     0.033652 -2.721641       1.0
  2020-12-29      0.020204     0.034986 -2.537322       1.0
  2020-12-30      0.017561     0.036941 -2.818702       1.0
  2020-12-31      0.015102     0.039203 -2.728766       1.0

  [1419 rows x 10 columns],
  ('1088 HK Equity vs 3993 HK Equity',
   5.0):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  1.973247  0.344299  1.788838  0.385438  0.051703      5.0
  2015-03-31  1.976301  0.327864  1.789498  0.386864  0.059964      5.0
  2015-04-01  1.982380  0.389336  1.789847  0.388313  0.041349      5.0
  2015-04-02  2.003640  0.500169  1.789921  0.389361  0.018973      5.0
  2015-04-08  2.028017  0.696143  1.790043  0.386558 -0.031126      5.0
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  2.162863  1.318283  1.675973  0.420592 -0.067568      5.0
  2020-12-28  2.165619  1.469026  1.676293  0.419294 -0.126627      5.0
  2020-12-29  2.160215  1.456753  1.676585  0.418044 -0.125358      5.0
  2020-12-30  2.151995  1.493578  1.676986  0.416511 -0.147083      5.0
  2020-12-31  2.149317  1.509397  1.677426  0.414882 -0.154330      5.0

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30      0.363396     0.375506 -0.830060       0.0
  2015-03-31      0.334907     0.328998 -0.835698       0.0
  2015-04-01      0.310329     0.292301 -0.920213       0.0
  2015-04-02      0.288648     0.262923 -1.025681       0.0
  2015-04-08      0.268637     0.239381 -1.252246       0.0
  ...                  ...          ...       ...       ...
  2020-12-24     -0.010037     0.035812 -1.606498       1.0
  2020-12-28     -0.012735     0.038350 -2.969799       1.0
  2020-12-29     -0.015534     0.040322 -2.723690       1.0
  2020-12-30     -0.018693     0.043035 -2.983379       1.0
  2020-12-31     -0.021703     0.046047 -2.880255       1.0

  [1419 rows x 10 columns],
  ('1088 HK Equity vs 1171 HK Equity',
   0.5):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  1.973247  0.110647  1.967370  0.345521 -0.032353      0.5
  2015-03-31  1.976301  0.146694  1.966876  0.342003 -0.040745      0.5
  2015-04-01  1.982380  0.149282  1.966474  0.338923 -0.034689      0.5
  2015-04-02  2.003640  0.207827  1.966428  0.332909 -0.031975      0.5
  2015-04-08  2.028017  0.463105  1.969586  0.287114 -0.074533      0.5
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  2.162863  0.509825  1.906870  0.417639  0.043070      0.5
  2020-12-28  2.165619  0.511625  1.907321  0.418189  0.044343      0.5
  2020-12-29  2.160215  0.498955  1.907795  0.418651  0.043532      0.5
  2020-12-30  2.151995  0.494086  1.908206  0.419014  0.036759      0.5
  2020-12-31  2.149317  0.494086  1.908583  0.419344  0.033543      0.5

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30      0.025212     0.126916 -0.453567       0.0
  2015-03-31      0.012877     0.091232 -0.587748       0.0
  2015-04-01      0.005360     0.074470 -0.537789       0.0
  2015-04-02     -0.000086     0.064184 -0.496846       0.0
  2015-04-08     -0.005193     0.057228 -1.211660       0.0
  ...                  ...          ...       ...       ...
  2020-12-24      0.056589     0.020975 -0.644536       1.0
  2020-12-28      0.056186     0.020974 -0.564667       1.0
  2020-12-29      0.055798     0.020990 -0.584406       1.0
  2020-12-30      0.055292     0.021078 -0.879255       1.0
  2020-12-31      0.054095     0.020207 -1.017075       1.0

  [1419 rows x 10 columns],
  ('1088 HK Equity vs 1171 HK Equity',
   1.0):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  1.973247  0.110647  1.960198  0.277831 -0.017692      1.0
  2015-03-31  1.976301  0.146694  1.959860  0.276724 -0.024153      1.0
  2015-04-01  1.982380  0.149282  1.959610  0.275852 -0.018410      1.0
  2015-04-02  2.003640  0.207827  1.959507  0.274551 -0.012926      1.0
  2015-04-08  2.028017  0.463105  1.960318  0.257460 -0.051533      1.0
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  2.162863  0.509825  1.878497  0.466137  0.046718      1.0
  2020-12-28  2.165619  0.511625  1.878846  0.466554  0.048072      1.0
  2020-12-29  2.160215  0.498955  1.879216  0.466920  0.048026      1.0
  2020-12-30  2.151995  0.494086  1.879544  0.467219  0.041605      1.0
  2020-12-31  2.149317  0.494086  1.879847  0.467494  0.038488      1.0

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30      0.080852     0.192114 -0.512941       0.0
  2015-03-31      0.062894     0.144006 -0.604466       0.0
  2015-04-01      0.050947     0.117730 -0.589126       0.0
  2015-04-02      0.042067     0.100609 -0.546606       0.0
  2015-04-08      0.034242     0.088392 -0.970389       0.0
  ...                  ...          ...       ...       ...
  2020-12-24      0.056558     0.020450 -0.481198      -1.0
  2020-12-28      0.056344     0.020470 -0.404094      -1.0
  2020-12-29      0.056149     0.020493 -0.396360      -1.0
  2020-12-30      0.055828     0.020569 -0.691521      -1.0
  2020-12-31      0.054685     0.019552 -0.828406      -1.0

  [1419 rows x 10 columns],
  ('1088 HK Equity vs 1171 HK Equity',
   5.0):                    y         x   alpha_t    beta_t  spread_t  obs_cov  \
  Date
  2015-03-30  1.973247  0.110647  1.848599  0.203033  0.102183      5.0
  2015-03-31  1.976301  0.146694  1.850029  0.204066  0.096336      5.0
  2015-04-01  1.982380  0.149282  1.851490  0.205175  0.100261      5.0
  2015-04-02  2.003640  0.207827  1.852919  0.207583  0.107579      5.0
  2015-04-08  2.028017  0.463105  1.853548  0.213040  0.075808      5.0
  ...              ...       ...       ...       ...       ...      ...
  2020-12-24  2.162863  0.509825  1.849861  0.557618  0.028715      5.0
  2020-12-28  2.165619  0.511625  1.849965  0.557726  0.030307      5.0
  2020-12-29  2.160215  0.498955  1.850078  0.557830  0.031805      5.0
  2020-12-30  2.151995  0.494086  1.850172  0.557911  0.026166      5.0
  2020-12-31  2.149317  0.494086  1.850257  0.557984  0.023369      5.0

              rolling_mean  rolling_std    zscore  position
  Date
  2015-03-30      0.378726     0.372542 -0.742313       0.0
  2015-03-31      0.350833     0.326411 -0.779681       0.0
  2015-04-01      0.327210     0.289768 -0.783211       0.0
  2015-04-02      0.306986     0.260052 -0.766795       0.0
  2015-04-08      0.288677     0.235458 -0.904059       0.0
  ...                  ...          ...       ...       ...
  2020-12-24      0.031327     0.020409 -0.127991      -1.0
  2020-12-28      0.031451     0.020379 -0.056095      -1.0
  2020-12-29      0.031608     0.020344  0.009690      -1.0

In [50]:
is_extraction = extractor(is_results)

In [51]:
is_extraction.head()

,date,strategy,pair,obs_cov,spread_t,position,spread_change,strategy_ret
1,2015-03-31,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.031353,1.0,0.016522,0.016522
2,2015-04-01,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.076066,1.0,-0.044714,-0.044714
3,2015-04-02,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.074835,1.0,0.001232,0.001232
4,2015-04-08,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.195027,1.0,-0.120192,-0.120192
5,2015-04-09,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.135044,1.0,0.059984,0.059984

In [52]:
is_volatility = pair_volatility(is_extraction)

In [53]:
is_volatility.head()

,date,strategy,pair,obs_cov,spread_t,position,spread_change,strategy_ret,pair_strategy_vol
3,2015-04-02,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.074835,1.0,0.001232,0.001232,0.043300
4,2015-04-08,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.195027,1.0,-0.120192,-0.120192,0.031345
5,2015-04-09,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.135044,1.0,0.059984,0.059984,0.062142
6,2015-04-10,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.180859,1.0,-0.045815,-0.045815,0.056931
7,2015-04-13,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.149536,1.0,0.031323,0.031323,0.054406

In [54]:
# Volatility plots
is_volatility_plots = pair_volatility_plots(
    vol_df = is_volatility,
    output_dir=PROJECT_ROOT / "outputs/volatility/in_sample")

Volatility plots saved to: /Users/ivanhung/Documents/GitHub/applied-project-06039211/outputs/volatility/in_sample

In [55]:
is_drawdown_values = drawdown_thresholds(is_volatility)

In [56]:
is_drawdown_values.head()

,date,strategy,pair,obs_cov,pair_strategy_vol,reduce_drawdown_threshold,close_drawdown_threshold
3,2015-04-02,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.043300,0.684640,1.369280
4,2015-04-08,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.031345,0.495612,0.991223
5,2015-04-09,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.062142,0.982552,1.965103
6,2015-04-10,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.056931,0.900157,1.800313
7,2015-04-13,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.054406,0.860236,1.720472

### Out-Of-Sample

In [57]:
oos_extraction = extractor(oos_results)

In [58]:
oos_extraction.head()

,date,strategy,pair,obs_cov,spread_t,position,spread_change,strategy_ret
1,2021-03-31,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.030023,0.0,0.032115,0.000000
2,2021-04-01,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.021998,0.0,-0.052021,-0.000000
3,2021-04-07,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.128066,0.0,-0.106068,-0.000000
4,2021-04-08,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.207898,1.0,-0.079833,-0.000000
5,2021-04-09,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.190909,1.0,0.016989,0.016989

In [59]:
oos_volatility = pair_volatility(oos_extraction)

In [60]:
oos_volatility.head()

,date,strategy,pair,obs_cov,spread_t,position,spread_change,strategy_ret,pair_strategy_vol
3,2021-04-07,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.128066,0.0,-0.106068,-0.000000,0.000000
4,2021-04-08,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.207898,1.0,-0.079833,-0.000000,0.000000
5,2021-04-09,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.190909,1.0,0.016989,0.016989,0.000000
6,2021-04-12,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.150558,1.0,0.040351,0.040351,0.006306
7,2021-04-13,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,-0.130813,1.0,0.019746,0.019746,0.014557

In [61]:
# Volatility plots
oos_volatility_plots = pair_volatility_plots(
    vol_df = oos_volatility,
    output_dir=PROJECT_ROOT / "outputs/volatility/out_of_sample")

Volatility plots saved to: /Users/ivanhung/Documents/GitHub/applied-project-06039211/outputs/volatility/out_of_sample

In [62]:
oos_drawdown_values = drawdown_thresholds(oos_volatility)

In [63]:
oos_drawdown_values.head()

,date,strategy,pair,obs_cov,pair_strategy_vol,reduce_drawdown_threshold,close_drawdown_threshold
3,2021-04-07,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.000000,0.000000,0.000000
4,2021-04-08,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.000000,0.000000,0.000000
5,2021-04-09,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.000000,0.000000,0.000000
6,2021-04-12,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.006306,0.099702,0.199404
7,2021-04-13,entry_1.5_exit_0.0,700 HK Equity vs 1347 HK Equity,0.5,0.014557,0.230164,0.460327

In [64]:
# Save drawdown_values to .pkl 
with open(PROJECT_ROOT / "data/dictionaries/is_drawdown_values.pkl", "wb") as f:
    pickle.dump(is_drawdown_values, f)

with open(PROJECT_ROOT / "data/dictionaries/oos_drawdown_values.pkl", "wb") as f:
    pickle.dump(oos_drawdown_values, f)